drop table if exists answers cascade;

create table answers(
  id int generated by default as identity,
  question_id int,
  body varchar(1000),
  date_written date,
  answerer_name varchar(60),
  answerer_email varchar(60),
  helpful int,
  reported int,
  photos jsonb default '[]'::jsonb,
  primary key(id),
  constraint fk_question
    foreign key(question_id)
      references questions(id)
      on delete cascade
);

create index answers_question_id_index on answers (question_id);
-- psql -U postgres questionsAndAnswers -f ETL/postgres/schemaAnswers.sql
