drop table if exists answers cascade;

create table answers(
  id int generated by default as identity,
  product_id int,
  written date,
  body varchar(1000),
  asker_name varchar(60),
  asker_email varchar(60),
  helpful int,
  reported int,
  primary key(id)
);

-- psql -U postgres questionsAndAnswers -f ETL/postgres/schemaTest.sql
